"""Add youtube_url to Video

Revision ID: 6a048bc0111b
Revises: e4bfb4ddb1b8
Create Date: 2025-07-09 00:22:21.115444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a048bc0111b'
down_revision: Union[str, Sequence[str], None] = 'e4bfb4ddb1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
