"""Add thumbnail column to playlists

Revision ID: 73c0300f5c5e
Revises: dd7ef9533b35
Create Date: 2025-07-09 00:09:21.747417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c0300f5c5e'
down_revision: Union[str, Sequence[str], None] = 'dd7ef9533b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'youtube_url')
    # ### end Alembic commands ###
