"""Add youtube_id to Playlist

Revision ID: d9426972195e
Revises: 6a048bc0111b
Create Date: 2025-07-09 00:57:44.393224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9426972195e'
down_revision: Union[str, Sequence[str], None] = '6a048bc0111b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('youtube_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'youtube_id')
    # ### end Alembic commands ###
