"""Add youtube_url to Video

Revision ID: e4bfb4ddb1b8
Revises: 73c0300f5c5e
Create Date: 2025-07-09 00:13:18.144021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bfb4ddb1b8'
down_revision: Union[str, Sequence[str], None] = '73c0300f5c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
